services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cinema
    image: cinema-image           
    env_file:
      - .env.dev
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: >
      sh -c "uv run python app/manage.py migrate --noinput &&
             uv run python app/manage.py runserver 0.0.0.0:8000"

  db:
    container_name: cinema-db
    image: postgres:13.0-alpine
    command: postgres -c 'max_connections=500'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.dev

volumes:
  postgres_data:
