[project]
name = "cinema"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django==4.2",
    "djangorestframework==3.16.1",
    "psycopg2-binary>=2.9.10",
]
